apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: freshrss

resources:
  - pvc.yaml
  - cronjob.yaml

images:
  - name: freshrss-bi-pipeline
    newName: registry.white.fm/freshrss-bi-pipeline
    newTag: "1.1.1"

generators:
  - ksops.yaml
