apiVersion: v1
kind: Secret
metadata:
    name: freshrss-bi-secrets
    namespace: freshrss
type: Opaque
stringData:
    FRESHRSS_USERNAME: ENC[AES256_GCM,data:zy57Pd+5,iv:f4Ehf2lMM4w/j9e212MkOJZUv7T5M2ThYODhHbYn4dM=,tag:U6ItHiscahUjrafjS0Gptg==,type:str]
    FRESHRSS_API_PASSWORD: ENC[AES256_GCM,data:QLt9xTNWN8QcjvduEbcYN3HMyg==,iv:qykGFD6g2SYsCFJ3GMCXMbuKkdheCASWDi//W2yNoEg=,tag:+pPpwJKKzZavWuadOkYj9Q==,type:str]
    AI_API_KEY: ENC[AES256_GCM,data:WCVQeIA=,iv:njDPyTrZBFar40KvPfdMg3yKhXNy7eW1SDPheZCrrKE=,tag:m4tLGnrSjSy5Hh9XSk++Yg==,type:str]
    WEBHOOK_URL: ""
    INFLUXDB_URL: ENC[AES256_GCM,data:tWMNLYnXZwFpvphV/gC0FoE3WJEyic04pGtazwTHxdtV0JF7mf5QH9ioxThB/S+8Kbf42g==,iv:onrSKCaLmyzaHFRoHISit7o0h2IqPC74vqsxNwwHxWI=,tag:iuqGa2eflHfeF1/c56Kp0Q==,type:str]
    INFLUXDB_ORG: ENC[AES256_GCM,data:luTK7Q==,iv:Le5DIqUKsIbwvaXQT2Ij8IZYD58BIwq7WGI4y37G0Wo=,tag:eyYPRQo4XhC3e5WJX8lbMw==,type:str]
    INFLUXDB_BUCKET: ENC[AES256_GCM,data:Pg9ifVgic5pZs9I=,iv:HsAHmUiZUj6PMF+kxjFdXhLyrEJceNYSG3sUwxa7e5o=,tag:liJ1QieHoPAs/mci5xAV8A==,type:str]
    INFLUXDB_TOKEN: ENC[AES256_GCM,data:talNaMvvz9MHr6h8d7r+5NLm2d0jNYl/RXVZWvKL6QUo26fScJwazyWWvHug/gSzsA6admbJIq/jdLCkjdYtIbI7DKRdB+6HfqjJ1vKxejpH/7aNkk58Kw==,iv:fHUKtI9QwxLyr43APxb3D4IfB49adFMiI1gjNU184hU=,tag:3SGGxudTpB732ADcuowLpQ==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjb3gxN1RrS2hMQWZ2N3JD
            bElXWDZ3SllabmNPaE5mbys1ZXhYZDEvb3pFCnhkTEZtbG1WZjVaQXJlU09WTlNj
            OG1Ba09xdnd1WXlZWEtxbjl4eExMa2sKLS0tIHZpQlUwUm4wNlNGM3VBSUJ1U1FU
            QlBUOEFUVXVubWVJVnVqeituRG8veEUKLxciX10eQWx22lvBGpKLEA8RfX7Fk9UB
            AEij9AJHsWJqVNQAj0uexlnLutpPZtsn6yDCxbcSz+4AQDu8PepfRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T18:46:46Z"
    mac: ENC[AES256_GCM,data:/63SEobxo6hwswm1ow8c1Ytq18GRgZiEVXqOpTyFCY259Uqrpu4XWObVrc9dGC9Zi5TQhfi4pF6g/gC8CXWkzxU6VUrmsYep4dtiLtmQXlsAaZpGMf7g+ELAoeDChFtTDy1e10FWO5ViD6dVxXpxnldIwhHdiiatyNsWn32J8/w=,iv:2+lxJWCWz8VF5rAcLYzpZvzQCg+LbYdjcUxws487naU=,tag:LTWM1vLyNwTC6fNyCqcjCw==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
