apiVersion: v1
kind: Secret
metadata:
    name: freshrss-bi-secrets
    namespace: freshrss
type: Opaque
stringData:
    FRESHRSS_USERNAME: ENC[AES256_GCM,data:zy57Pd+5,iv:f4Ehf2lMM4w/j9e212MkOJZUv7T5M2ThYODhHbYn4dM=,tag:U6ItHiscahUjrafjS0Gptg==,type:str]
    FRESHRSS_API_PASSWORD: ENC[AES256_GCM,data:QLt9xTNWN8QcjvduEbcYN3HMyg==,iv:qykGFD6g2SYsCFJ3GMCXMbuKkdheCASWDi//W2yNoEg=,tag:+pPpwJKKzZavWuadOkYj9Q==,type:str]
    AI_API_KEY: ENC[AES256_GCM,data:WCVQeIA=,iv:njDPyTrZBFar40KvPfdMg3yKhXNy7eW1SDPheZCrrKE=,tag:m4tLGnrSjSy5Hh9XSk++Yg==,type:str]
    WEBHOOK_URL: ENC[AES256_GCM,data:UI4QgftkBhzt0tl5HzFtNJfmx6ubVR7lxfWsRk6ydxXDr3khVAn+cPhwmn7F7XnJOeqfSMSyFJs4uwUABcz5KNxaDZuZgTtquR+fxgPXXbUTwqZKW942jnooN2YK6w0=,iv:x4kzjAOxLp2WAoGCFqBCRVx97OJwu2l4wK0Z5j0pvXw=,tag:9Iz6oDyZZRgctS+h80C73g==,type:str]
    INFLUXDB_URL: ENC[AES256_GCM,data:tWMNLYnXZwFpvphV/gC0FoE3WJEyic04pGtazwTHxdtV0JF7mf5QH9ioxThB/S+8Kbf42g==,iv:onrSKCaLmyzaHFRoHISit7o0h2IqPC74vqsxNwwHxWI=,tag:iuqGa2eflHfeF1/c56Kp0Q==,type:str]
    INFLUXDB_ORG: ENC[AES256_GCM,data:NpVehrY+D+RjMQ==,iv:0jNog8tSQYiiT8Hv9REBtcQh8iVNsdTDPRvuyFdOdz4=,tag:7p9JOvS7snVvgNZXDCsUOA==,type:str]
    INFLUXDB_BUCKET: ENC[AES256_GCM,data:Pg9ifVgic5pZs9I=,iv:HsAHmUiZUj6PMF+kxjFdXhLyrEJceNYSG3sUwxa7e5o=,tag:liJ1QieHoPAs/mci5xAV8A==,type:str]
    INFLUXDB_TOKEN: ENC[AES256_GCM,data:talNaMvvz9MHr6h8d7r+5NLm2d0jNYl/RXVZWvKL6QUo26fScJwazyWWvHug/gSzsA6admbJIq/jdLCkjdYtIbI7DKRdB+6HfqjJ1vKxejpH/7aNkk58Kw==,iv:fHUKtI9QwxLyr43APxb3D4IfB49adFMiI1gjNU184hU=,tag:3SGGxudTpB732ADcuowLpQ==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjb3gxN1RrS2hMQWZ2N3JD
            bElXWDZ3SllabmNPaE5mbys1ZXhYZDEvb3pFCnhkTEZtbG1WZjVaQXJlU09WTlNj
            OG1Ba09xdnd1WXlZWEtxbjl4eExMa2sKLS0tIHZpQlUwUm4wNlNGM3VBSUJ1U1FU
            QlBUOEFUVXVubWVJVnVqeituRG8veEUKLxciX10eQWx22lvBGpKLEA8RfX7Fk9UB
            AEij9AJHsWJqVNQAj0uexlnLutpPZtsn6yDCxbcSz+4AQDu8PepfRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T05:26:35Z"
    mac: ENC[AES256_GCM,data:/e7Bcut3gyFp2lbOkMfKBzq8fuC9xa1NvoJJMLDcJpJQwbokfEEKXgzqLs8d2ccEo7EFBRpgBwRZ4Y+MBgeWCdBW1JbBRRHFsiKYkg27iH6cCIp/Wyp2OA4cvB6JHShPgNtErJ6tWDPN75urJrkW+12CMTW1Ae7fJ7SpN45DG5Y=,iv:AfAF7qBLqnzP4JHMnuiSABiuQyOqfFoMo7uMIMNdxLM=,tag:mkTmzI/ffyRJdWAjDAcMvQ==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
