apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcharr-celery
  namespace: dispatcharr
  labels:
    app: dispatcharr-celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcharr-celery
  template:
    metadata:
      labels:
        app: dispatcharr-celery
    spec:
      enableServiceLinks: false
      containers:
        - name: celery
          image: ghcr.io/dispatcharr/dispatcharr:latest
          command:
            - bash
            - -c
            - "cd /app && nice -n 5 celery -A dispatcharr worker -l info"
          env:
            - name: POSTGRES_HOST
              value: db
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: dispatcharr-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: dispatcharr-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dispatcharr-secret
                  key: POSTGRES_PASSWORD
            - name: REDIS_HOST
              value: redis
            - name: CELERY_BROKER_URL
              value: redis://redis:6379/0
