apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dispatcharr-ingress
  namespace: dispatcharr
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - tv.white.fm
      secretName: tv-white-fm-tls
  rules:
    - host: tv.white.fm
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dispatcharr-web
                port:
                  number: 9191
