apiVersion: apps/v1
kind: Deployment
metadata:
  name: meremedical
  namespace: meremedical
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meremedical
  template:
    metadata:
      labels:
        app: meremedical
    spec:
      containers:
        - name: meremedical
          image: cfu288/mere-medical:2025.11.21
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: meremedical-env