apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: meremedical

resources:
  - 00-namespace.yaml
  - 10-deployment.yaml
  - 20-service.yaml
  - 40-ingress.yaml

generators:
  - ksops.yaml