apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - 05-config.yaml
#  - 10-pvc.yaml
  - 20-deployment.yaml
  - 30-svc.yaml
  - 40-ingress.yaml
  
generators:
  - ksops.yaml

images:
  - name: registry
    newTag: "3"