apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-audiobookshelf-config
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: pvc-c4aa3a05-2c15-4c7f-b8d6-1ae68fcff584
  resources:
    requests:
      storage: 10Gi
