apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myspeed

resources:
  - 00-namespace.yaml
  - 10-deployment.yaml
  - 20-service.yaml
# - 30-pvc.yaml
  - 40-ingress.yaml

images:
  - name: germannewsmaker/myspeed
    newTag: "1.0.9"