apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - 15-ingress.yaml
#  - 20-synology-pvc.yaml
#  - 21-synology-pv.yaml
  - 25-longhorn-pvc.yaml
  - 50-deployment.yaml
  - 60-svc.yaml

images:
  - name: ghcr.io/advplyr/audiobookshelf
    newTag: 2.32.1