
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - authentik-media.yaml
  - authentik-postgres.yaml
  - redis-data.yaml
  - authentik-media-pv.yaml
  - authentik-postgres-pv.yaml
  - redis-data-pv.yaml