apiVersion: v1
kind: ConfigMap
metadata:
  name: everydocs-web-config
  namespace: everydocs
data:
  config.js: |
    window.EVERYDOCS_CORE_URL = "http://everydocs-core.everydocs.svc.cluster.local:5678";