apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 # - allow-cloudflared-to-homarr.yaml
#  - homarr-cloudflared-authentik.yaml
  - homarr-deployment.yaml
#  - homarr-ingress-network-policy.yaml
  - homarr-ingress.yaml
  - homarr-pvc.yaml
  - homarr-rbac.yaml
  - homarr-service.yaml
  - homarr-tls.yaml
  - namespace.yaml
#  - allow-uptime-kuma.yaml
generators:
  - ksops.yaml

images:
  - name: ghcr.io/homarr-labs/homarr
    newTag: "v1.48.0"