apiVersion: apps/v1
kind: Deployment
metadata:
  name: cybether-backend
  namespace: cybether
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cybether-backend
  template:
    metadata:
      labels:
        app: cybether-backend
    spec:
      containers:
        - name: cybether-backend

          # renovate: datasource=docker depName=registry.white.fm/cybether/backend
          image: registry.white.fm/cybether/backend:1.0.0

          ports:
            - containerPort: 5000

          env:
            - name: DB_HOST
              value: "cybether-postgres.cybether.svc.cluster.local"
            - name: DB_PORT
              value: "5432"

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cybether-db-secret
                  key: POSTGRES_USER

            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: cybether-db-secret
                  key: POSTGRES_PASSWORD

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: cybether-db-secret
                  key: POSTGRES_DB

            - name: FLASK_ENV
              value: "production"