apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - 10-pvc.yaml
  - 20-statefulset.yaml
  - 30-svc-backend.yaml
  - 31-svc-frontend.yaml
  - 32-svc-postgres.yaml
  - 40-deployment-backend.yaml
  - 45-deployment-frontend.yaml
  - 50-ingress.yaml

generators:
  - ksops.yaml