apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postfix-service.yaml
  - postfix.yaml
  - namespace.yaml

generators:
  - ksops.yaml

images:
  - name: juanluisbaptiste/postfix
    newTag: "1.8.0"