apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyberchef
  annotations:
    renovatebot/update-container-image: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyberchef
  template:
    metadata:
      labels:
        app: cyberchef
    spec:
      containers:
        - name: cyberchef
          image: ghcr.io/gchq/cyberchef:10.19.4 # renovate: datasource=github-releases depName=gchq/CyberChef
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi