apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - 10-deployment.yaml
  - 20-service.yaml
  - 50-ingress.yaml

images:
  - name: ghcr.io/gchq/cyberchef
    newTag: "10.21.0"