apiVersion: v1
kind: ConfigMap
metadata:
    name: maubot-config
    namespace: matrix
data:
    config.yaml: ENC[AES256_GCM,data:eP5yLvvayJrwcPxk07eI2BJG3aHShvAzyORpcmrCTBR8AkWANsxEX8kE+eF1Hiozy51zov1gKCyksMN0+clpT88HtLyAsNI/XnOZcs49ubtvNIRE0Fv4Lqh7F6LHKi0uz5brQD0fkGlFu/I64YDX3qEuyXcpFGgxyDdVQoMP5eym7yl/PY+MkiV9JQoS8fYLSYl3efqQn6K/THU3LNm7nld2YXBuRVms1r3RUubNBDROUAGrJ6Lj900OYDIuWq+QT18sAz3ACFdsj76pbdTGcaa0pmDFhIg2xxf5SdH5S6QkzNxHormGlitnAwe0HkzOl6yvHg1k0SWgiQqIGzueJuOX0iUY+PJlXVNFCbbm0PiY6nFUss60vZ46DBIQMxOo51YBzOk/325VFqfb8wRpqMs44CdDDDwnhvndlgxFwNzyK8DRghR7y/n8ZimULWOOEkfN++rJZukF8PXRp/Ydx6anT2OsvtafEoIYJnpK7JY70FYPmm36HSCcK5m9UYoudcxq1nTiMoEXt/9BbgjPz7jGYHb4JucgM5dl4s/q9qfV5rGnmKNMIn5nLOAe/s+dUiyhvHuyIqzo7VVYNGFeb7Ei/nRWrqt3+oqDWdpk0TIi3ZR4R/0SpvF5mwPOcUIRBendqexAu6caAEZWVhx1TOa+T7XsWj9mwIKJA8FDP7BiMcwZegQ2xZw2J1MKW8np3YLwWS9yKbrT9t55wlVIUrD791f9kK+JjdtTv8Oj9MrLnweppnJPIkW4ENoplPk4bpydVmgwLYiPsYJEvTRH4kcw1axsFmWoIPnZe0cgK0v5RNnDTgxX0KZ45ufWCD81LbSdHZLmT+bv2K4qPlobpYm8ML0aoWo9aBvY7frT+lO+lLJ7J+Z7CvdeSxc2ibU0fRFuw6Ea/FD0ADm9/l1mRfAtugYC6PLKYUJ78EpyAiFNgCMrl/mfoiG+b5ggBO7T0anNL+zItAWSP/KO,iv:SptWdRiVo1d7T5no1vrTMaZ0w5CoAItHwH6d/RKY0rs=,tag:5hCUN0bTaoOraWxjGWOwXw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSkdxL01HSGpXNmRNQUQr
            bXR2bHg3cTBnWTJwNFRVZEphYURCek1kTzFzCmxwNUZEY3g4K0M2NzBRSVRMR1V2
            NFVGRzF4TkJXejJjcWF5WnJ4eFQ1YUUKLS0tIEZkUTUwMTFmekF4S3dYb3dlUHpV
            VkRaWEtpK1pjWEtlRXdwbG1VNzA1dDgK4YKThB/TFmfCGUiDzQ3973wle/yd3owp
            mi4aSPqrUPdmSLvJFPZBrM5qZLVEYCvqxcUs4Z7wQdSpIOToM/wrmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T04:37:40Z"
    mac: ENC[AES256_GCM,data:Q8W7t9WeNcriYOp7ZLuGcZTksG0Ua9WADMI6HePXiLiBOiEpnW6U81De/KFNsebGlJYs2b+CtIXVr/1GvYajoZfbiKoyccB55jNvFXumIpzLCh96lO9G370p5VJMQbGaBHwJO86sD+EAKyE0BVeySKq7rV6Kxa9cHvEdvX58jwM=,iv:KMh9aNArkuz67CF4GlxTa7I33M+mo5ab5LWqADFIIFs=,tag:F3bdTjDESCoakDtAzDhJ6Q==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
