apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: paperless

resources:
  - 00-namespace.yaml
  - 10-deployment.yaml
  - 11-deployment-redis.yaml
  - 12-deployment-postgres.yaml
  - 20-service.yaml
  - 21-service-redis.yaml
  - 22-service-postgres.yaml
  - 30-pvc-paperless.yaml
  - 31-pv-files.yaml
  - 50-ingress.yaml

generators:
  - ksops.yaml

images:
  - name: ghcr.io/paperless-ngx/paperless-ngx
    newTag: 2.20.3