apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: calibre

resources:
  - 00-namespace.yaml
  - 05-pvc-calibre-web-config.yaml
  - 10-deployment-calibre-web.yaml
  - 20-svc-calibre-web.yaml
  - 30-ingress-calibre-web.yaml