apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik

generators:
  - ksops.yaml

resources: []

helmCharts:
  - name: authentik
    releaseName: authentik
    version: 2025.10.3
    repo: https://charts.goauthentik.io
    valuesFile: values.yaml
    includeCRDs: true
    namespace: authentik
