apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trivy

resources:
  - 00-namespace.yaml
  - 05-serviceaccount.yaml
  - 06-clusterrole.yaml
  - 07-clusterrolebinding.yaml
  - 10-job.yaml
