apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

  - adsb
  - ai-stack
  - audiobookshelf
  - authentik
  - convos
  - cybether
  - freshrss
  - homarr
  - matrix
  - myspeed
  - observability
  - ombi
  - portainer
  - registry
  - snappymail
  - tautulli
  - uptime-kuma
