apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snappymail
  namespace: snappymail
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: nginx
  rules:
    - host: mail.white.fm
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: snappymail
                port:
                  number: 8888
  tls:
    - hosts:
        - mail.white.fm
      secretName: snappymail-tls