apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - 20-pv-calibre.yaml
  - 25-pvc-calibre.yaml
  - 30-deployment.yaml
  - 40-svc.yaml
  - 50-ingress.yaml

