apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: calibre

resources:
  - 00-namespace.yaml
  - 20-pv-calibre.yaml
  - 25-pvc-calibre.yaml
  - 30-deployment.yaml
  - 40-svc.yaml
  - 50-ingress.yaml
  - 60-pvc-calibre-web-config.yaml
  - 70-deployment-calibre-web.yaml
  - 80-svc-calibre-web.yaml
  - 90-ingress-calibre-web.yaml

images:
  - name: lscr.io/linuxserver/calibre
    newTag: "v8.16.2-ls374"
  - name: lscr.io/linuxserver/calibre-web
    newTag: "0.6.25-ls362"