apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#  - allow-uptime-kuma.yaml
  - cloudflared-namespace.yaml
  - cloudflared.yaml
generators:
  - ksops.yaml

images:
  - name: cloudflare/cloudflared
    newTag: "2026.1.2"