apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik-ingress.yaml
  - allow-egress-dns-and-kubernetes.yaml
  - allow-ingress.yaml
  - allow-cloudflared-to-authentik.yaml
  - allow-postgres.yaml
  - allow-redis.yaml
