apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 # - allow-authentik-all.yaml
 # - allow-authentik-to-cyberchef.yaml
 # - allow-authentik-egress-to-cyberchef.yaml
 # - allow-authentik-to-fr24.yaml
 # - allow-authentik-to-freshrss.yaml
 # - allow-authentik-to-longhorn.yaml
 # - allow-authentik-to-matrix.yaml
 # - allow-cloudflared-to-audiobookshelf.yaml
 # - allow-cloudflared-to-longhorn.yaml
 # - allow-cloudflared-to-ombi.yaml
 # - allow-cloudflared-to-tautulli.yaml
 # - allow-homepage-to-uptime-kuma.yaml
 # - allow-homepage-to-portainer.yaml
 # - allow-homepage-to-tautulli.yaml
 # - allow-homepage-to-immich.yaml
 # - allow-homepage-to-authentik.yaml
 # - allow-ingress-nginx-to-argocd.yaml
 # - allow-ingress-nginx-to-audiobookshelf.yaml
#  - allow-ingress-nginx-to-homarr.yaml
#  - allow-ingress-nginx-to-longhorn.yaml
#  - allow-ingress-nginx-to-ombi.yaml
#  - allow-ingress-nginx-to-portainer.#yaml
#  - allow-ingress-nginx-to-rancher.yaml
#  - allow-ingress-nginx-to-registry.yaml
#  - allow-ingress-nginx-to-tautulli.yaml
#  - allow-ingress-nginx-to-tar1090.yaml
#  - allow-uptime-kuma-to-authentik.yaml
#  - allow-uptime-kuma-to-ombi.yaml
#  - allow-uptime-kuma-to-portainer.yaml
#  - allow-uptime-kuma-to-tautulli.yaml
#  - nginx-namespace.yaml
  - rke2-ingress-nginx-helmchartconfig.yaml
  - service-rke2-ingress-nginx-controller.yaml
