apiVersion: v1
kind: ConfigMap
metadata:
    name: feeder-config
    namespace: adsb
data:
    FEEDER_TZ: ENC[AES256_GCM,data:9FvlEhHxg8zIGluHKcUEAw==,iv:zmiDdH2vqbU3owUhuaSBwuY0OfFYi4HAVGGjIjx3nm8=,tag:sYLY1WHnsqvxuAfpJyQDGw==,type:str]
    ADSB_SDR_SERIAL: ENC[AES256_GCM,data:n409dCihJUg=,iv:JaVZzXqGhdWSmuEbFeN6ir67l0yAMeQWG1zZZK3dgS0=,tag:eEsIUneGcB7IGRmMk6f4bw==,type:str]
    ADSB_SDR_PPM: ENC[AES256_GCM,data:Aw==,iv:qhf6FSeHVxIdjsu8QQbx0JhZTcef+7K1jlJpAZkd24U=,tag:x3/+chMYrAyFGs+KbnSUeQ==,type:str]
    FEEDER_LAT: ENC[AES256_GCM,data:m/MK/RllDfGX,iv:E6TbxpV7shgWI15oGGEnDhtFUy8ewburFrFAggtuz0I=,tag:aE4SRB/e9ZZ3ueXqK3ksOQ==,type:str]
    FEEDER_LONG: ENC[AES256_GCM,data:1N6Txo0O0DCUqE27,iv:TR06WbWNI6iKb0UYsPFaHnYYDFZByvdpQJlrZL2ROpc=,tag:4E8BJCcL8a1CMq0AX5lD6w==,type:str]
    FEEDER_ALT_M: ENC[AES256_GCM,data:tojZThO9lg==,iv:7iXxdfSTWaSCxDBt3CFDdsTXpPF91fQSM4WAM9751/o=,tag:uYK+MDnGvUjEW+GAvC+Cuw==,type:str]
    FEEDER_ALT_FT: ENC[AES256_GCM,data:Vbms,iv:VuhaAusC256D7CQTaZhiL0fuaIDs/SUl2vnkBFdb3Qk=,tag:R4eL0syl+KI8uFQGx2OQsA==,type:str]
    FEEDER_NAME: ENC[AES256_GCM,data:EuBazyIl0MiGwqM=,iv:H1kHV1NXupzI7n1/n39nxOFfQuFW0y4qKKIGB6solT8=,tag:mN50p7pydl3UwZRnSJobJQ==,type:str]
    #ENC[AES256_GCM,data:SNWszYG7ZN1xlgNO+Q6SzMHiRMMeRPDnCkSAYPXWOrFQiKeepswXOi8khq1HoDAdcJmtGcQ=,iv:9BwTGsrZqhTVnFgogbNZu9FtBsv1vsLsaasQ5gWzpCw=,tag:A+0VFX8KLwnEIcJWJ7rURw==,type:comment]
    #ENC[AES256_GCM,data:uiRaIZ2RFPS4uNI4XbGYA2fwEi6LWVO8N1cK8RlAX5Djtec=,iv:5C480JR4YutNLH/rVC7xC86qI1C0iuwSfC7ipP4DZ1A=,tag:IXwf3D9zVGDk+E87NMc0Rg==,type:comment]
    #ENC[AES256_GCM,data:4fXhgj7FDBEPEIOWXv8kdr5e2pYkgvFrGYUSlC7L7p0D2OUV8gvCJBkr5EOE1Xk=,iv:tXTVF88Xn43O+OAsOCXNPsENl2gTs5xVyom50s2+lvU=,tag:xA5BVrQ8xc56RPmjQBErcQ==,type:comment]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZ0ZPL3E4WmM3SWE1WS95
            MU1lUytPY3Rsd2NQcTFoL0JPYVV4QW92QWpZCk5HbkhCbld5U1BaMHNKNTZyV01Y
            ZjVZcWlGLzdyYk9zWWdMUktka1ZWeEkKLS0tIFVzSkM0MmNGcWpxeStkVS80VjhJ
            WE9CaVJTSXZpQkhHbFYxei9tM1h5cncKTILBBYEYFKEOHcO980dqE20hlNEkhTQJ
            3trWo5iZP2NwwknDvTTrd9xsq9qOU4qf2ftg3/WD7G/cUtsI1BtMHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T05:38:09Z"
    mac: ENC[AES256_GCM,data:1EH387WR3bXB4XJNDDzq0cUPNqsPkFVR5QrCV7FfSRdn12F+fcDZnF9eOcEH8fe7f+5fjHx2RuhFtMMawHX8UOfHZrFqK3u2R3/m9VH41y6i1EV05+zloG5gAhuXwJMpy4l6GkuHEBWMIsiPC/xK9Vim1RodsdIRk4Ome9SrCLQ=,iv:467QmWbCk919284TBiOCm5ew1KOTvoPwvpB4+zfpJhg=,tag:ZDOeu6Z7mKoBMHO0JKuMbQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
