apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openhamclock

resources:
  - 00-namespace.yaml
  - 10-pvc.yaml
  - 20-deployment.yaml
  - 30-service.yaml
  - 40-ingress.yaml

commonLabels:
  managed-by: argocd
  app.kubernetes.io/part-of: openhamclock

images:
  - name: ggilman/openhamclock
    newTag: "1.2"
