apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yaml
  - 01-crds.yaml
  - 02-crds.yaml
  - 05-serviceaccounts.yaml
  - 06-serviceaccounts.yaml
  - 07-rbac.yaml
  - 08-controller.yaml
  - 09-speaker.yaml
  - 10-ip-pool.yaml
  - 11-l2advertisement.yaml