apiVersion: apps/v1
kind: Deployment
metadata:
  name: matrix-webhooks
  namespace: matrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matrix-webhooks
  template:
    metadata:
      labels:
        app: matrix-webhooks
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: webhooks
          image: jceloria/matrix-encrypted-webhooks:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: matrix-webhooks-secret
          volumeMounts:
            - name: config
              mountPath: /webhooks-config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: matrix-webhooks-config
