apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik.yaml
  - authentik-worker.yaml
  - postgresql-deploy.yaml
  - redis.yaml

images:
  - name: ghcr.io/goauthentik/server
    newTag: "2025.12.4"

  - name: postgres
    newTag: "16-alpine"

  - name: redis
    newTag: "8.6-alpine"