apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik.yaml
  - authentik-worker.yaml
  - postgresql-deploy.yaml
  - redis.yaml

images:
  - name: ghcr.io/goauthentik/server:2025.8.4
    newTag: "2025.8.4"

  - name: postgres
    newTag: "16-alpine"

  - name: redis
    newTag: "7.2-alpine"