apiVersion: apps/v1
kind: Deployment
metadata:
  name: raven-redis
  namespace: raven
  labels:
    app: raven-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raven-redis
  template:
    metadata:
      labels:
        app: raven-redis
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
