apiVersion: apps/v1
kind: Deployment
metadata:
  name: raven
  namespace: raven
  labels:
    app: raven
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raven
  template:
    metadata:
      labels:
        app: raven
    spec:
      containers:
        - name: raven
          image: qeeqbox/raven:latest
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
