apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: raven-ingress
  namespace: raven
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - threats.white.fm
      secretName: threats-white-fm-tls
  rules:
    - host: threats.white.fm
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: raven
                port:
                  number: 8000
