apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yaml
  - 10-deployment-redis.yaml
  - 15-service-redis.yaml
  - 20-deployment-raven.yaml
  - 25-service-raven.yaml
  - 60-ingress.yaml
