apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - data-matrix-postgresql-0.yaml
  - data-matrix-redis-0.yaml
  - matrix-webhooks-config.yaml
  - maubot-data.yaml
  - synapse-data.yaml

  - data-matrix-postgresql-0-pv.yaml
  - data-matrix-redis-0-pv.yaml
  - matrix-webhooks-config-pv.yaml
  - maubot-data-pv.yaml
  - synapse-data-pv.yaml
