apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - data-matrix-postgresql-0.yaml
  - data-matrix-redis-0.yaml
  - matrix-webhooks-config.yaml
  - maubot-data.yaml
  - synapse-data.yaml
