apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrix-webhooks-config
  namespace: matrix
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: pvc-ec7f70ed-86ca-4644-8cbe-8b2c546aa185
  resources:
    requests:
      storage: 1Gi
