apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
#  - 10-pvc.yaml
  - 20-kuma-deployment.yaml
  - 30-kuma-svc.yaml
  - 50-ingress.yaml
#  - 55-network-policy.yaml

images:
  - name: louislam/uptime-kuma
    newTag: "2.0.2"