apiVersion: apps/v1
kind: Deployment
metadata:
  name: thelounge
  namespace: convos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thelounge
  template:
    metadata:
      labels:
        app: thelounge
    spec:
      containers:
        - name: thelounge
          image: ghcr.io/thelounge/thelounge:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: thelounge-data
              mountPath: /var/opt/thelounge
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
      volumes:
        - name: thelounge-data
          persistentVolumeClaim:
            claimName: thelounge-data