apiVersion: apps/v1
kind: Deployment
metadata:
  name: thelounge
  namespace: convos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thelounge
  template:
    metadata:
      labels:
        app: thelounge
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      initContainers:
        - name: fix-permissions
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              chown -R 1000:1000 /var/opt/thelounge || true
              chmod -R g+rwX /var/opt/thelounge || true
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: thelounge-data
              mountPath: /var/opt/thelounge

      containers:
        - name: thelounge
          image: ghcr.io/thelounge/thelounge
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: thelounge-data
              mountPath: /var/opt/thelounge
      volumes:
        - name: thelounge-data
          persistentVolumeClaim:
            claimName: thelounge-data