apiVersion: apps/v1
kind: Deployment
metadata:
  name: znc
  namespace: convos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: znc
  template:
    metadata:
      labels:
        app: znc
    spec:
      containers:
        - name: znc
          image: znc
          imagePullPolicy: IfNotPresent

          ports:
            - name: irc
              containerPort: 6697

          volumeMounts:
            - name: znc-data
              mountPath: /znc-data

          env:
            - name: ZNC_DATADIR
              value: /znc-data

      volumes:
        - name: znc-data
          persistentVolumeClaim:
            claimName: znc-data