apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yaml
#  - 10-pvc.yaml
  - 20-deployment.yaml
  - 30-service.yaml
  - 40-ingress.yaml
  - 50-metallb.yaml
  
commonLabels:
  app.kubernetes.io/name: convos
  app.kubernetes.io/instance: convos

generators:
  - ksops.yaml

images:
  - name: znc
    newTag: 1.10.1