apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - 10-pvc.yaml
  - 11-secret.yaml
  - 20-deployment.yaml
  - 30-service.yaml
  - 40-authentik-service.yaml
  - 50-ingress.yaml

generators:
  - ksops.yaml

images:
  - name: pbogre/jetlog
    newTag: "1.1.7"