apiVersion: apps/v1
kind: Deployment
metadata:
  name: monica
  namespace: monica
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monica
  template:
    metadata:
      labels:
        app: monica
    spec:
      containers:
        - name: monica
          image: monica:5.0-apache
          env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: monica-app-secrets
                  key: APP_KEY

            - name: APP_URL
              valueFrom:
                secretKeyRef:
                  name: monica-app-secrets
                  key: APP_URL

            - name: TRUSTED_PROXIES
              value: "*"

            - name: DB_CONNECTION
              value: pgsql
            - name: DB_HOST
              value: monica-postgresql.monica.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: monica
            - name: DB_USERNAME
              value: monica
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: monica-postgresql
                  key: password

            - name: REDIS_HOST
              value: monica-redis
            - name: REDIS_PORT
              value: "6379"

            - name: SESSION_DRIVER
              value: redis
            - name: SESSION_CONNECTION
              value: default
            - name: CACHE_DRIVER
              value: redis
            - name: QUEUE_CONNECTION
              value: redis

          ports:
            - containerPort: 80

          volumeMounts:
            - name: data
              mountPath: /var/www/html/storage

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: monica-data