apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monica
  namespace: monica
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

    nginx.ingress.kubernetes.io/auth-url: "https://authentik.white.fm/outpost.goauthentik.io/auth/nginx"
    nginx.ingress.kubernetes.io/auth-signin: "https://authentik.white.fm/outpost.goauthentik.io/start?rd=$escaped_request_uri"

    nginx.ingress.kubernetes.io/auth-snippet: |
      if ($request_uri ~* "\.(css|js|png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf|eot|json|map)$") {
        return 200;
      }

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - monica.white.fm
      secretName: monica-white-fm-tls
  rules:
    - host: monica.white.fm
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monica
                port:
                  number: 80