apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monica
  namespace: monica
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    authentik.ingress.manager/enabled: "true"
    authentik.ingress.manager/provider: "monica"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - monica.white.fm
      secretName: monica-white-fm-tls
  rules:
    - host: monica.white.fm
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monica
                port:
                  number: 80