apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yaml
  - 10-postgres.yaml
  - 15-service-postgres.yaml
  - 20-pvc.yaml
  - 20-redis.yaml
  - 25-service-redis.yaml
  - 30-deployment.yaml
  - 35-configmap.yaml
  - 40-service.yaml
  - 50-ingress.yaml

commonLabels:
  app.kubernetes.io/name: monica
  app.kubernetes.io/instance: monica

generators:
  - ksops.yaml