apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yaml
  - 10-mariadb.yaml
  - 15-service-mariadb.yaml
  - 20-pvc.yaml
  - 20-redis.yaml
  - 21-pvc-redis.yaml
  - 25-service-redis.yaml
  - 23-memcached.yaml
  - 24-pvc-meilisearch.yaml
  - 26-meilisearch.yaml
  - 27-mailpit.yaml
  - 30-configmap.yaml
  - 30-deployment.yaml
  - 33-queue-deployment.yaml
  - 34-cronjob.yaml
  - 40-service.yaml
  - 41-authentik-service.yaml
  - 50-ingress.yaml

commonLabels:
  app.kubernetes.io/name: monica
  app.kubernetes.io/instance: monica

generators:
  - ksops.yaml
